import { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

type Me={id:number;username:string;name:string;email:string;role:'ADMIN'|'MANAGER'|'USER';manager:string|null}
type Task={id:number;title:string;description:string;assigned_to:number;assigned_to_name:string;status:'TODO'|'IN_PROGRESS'|'DONE';created_at:string;updated_at:string}
type User={id:number;name:string;username:string;email:string;role:string;manager:number|null}

const API=import.meta.env.VITE_API_URL || '/api'
async function api(path:string, options:RequestInit={}){const token=localStorage.getItem('access');const headers=new Headers(options.headers);if(options.body)headers.set('Content-Type','application/json');if(token)headers.set('Authorization',`Bearer ${token}`);const r=await fetch(`${API}${path}`,{...options,headers});if(!r.ok)throw new Error((await r.json().catch(()=>({detail:'Request failed'}))).detail||'Request failed');return r.status===204?null:r.json()}

function App(){
 const [me,setMe]=useState<Me|null>(null); const [tasks,setTasks]=useState<Task[]>([]); const [users,setUsers]=useState<User[]>([]); const [login,setLogin]=useState({username:'',password:''}); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [filter,setFilter]=useState('ALL'); const [view,setView]=useState<'dashboard'|'tasks'|'people'>('dashboard')
 const [draft,setDraft]=useState({title:'',description:'',assigned_to:'',status:'TODO'}); const [showNew,setShowNew]=useState(false)
 const load=async()=>{try{const [m,t]=await Promise.all([api('/me/'),api('/tasks/')]);setMe(m);setTasks(t);if(m.role!=='USER')setUsers(await api('/users/'))}catch(e){localStorage.removeItem('access');setMe(null);setError('Session expired. Please sign in again.')}finally{setLoading(false)}}
 useEffect(()=>{if(localStorage.getItem('access'))load();else setLoading(false)},[])
 const stats=useMemo(()=>({todo:tasks.filter(t=>t.status==='TODO').length,progress:tasks.filter(t=>t.status==='IN_PROGRESS').length,done:tasks.filter(t=>t.status==='DONE').length}),[tasks])
 const filtered=tasks.filter(t=>filter==='ALL'||t.status===filter)
 const signIn=async(e:React.FormEvent)=>{e.preventDefault();setError('');try{const r=await api('/token/',{method:'POST',body:JSON.stringify(login)});localStorage.setItem('access',r.access);localStorage.setItem('refresh',r.refresh);await load()}catch(e){setError('Invalid username or password.')}}
 const signOut=()=>{localStorage.clear();setMe(null);setTasks([]);setUsers([])}
 const createTask=async(e:React.FormEvent)=>{e.preventDefault();try{await api('/tasks/',{method:'POST',body:JSON.stringify({...draft,assigned_to:Number(draft.assigned_to)})});setDraft({title:'',description:'',assigned_to:'',status:'TODO'});setShowNew(false);await load()}catch(e){setError((e as Error).message)}}
 const updateStatus=async(t:Task,status:string)=>{try{await api(`/tasks/${t.id}/`,{method:'PATCH',body:JSON.stringify({status})});await load()}catch(e){setError((e as Error).message)}}
 const remove=async(t:Task)=>{if(!confirm(`Delete “${t.title}”?`))return;try{await api(`/tasks/${t.id}/`,{method:'DELETE'});await load()}catch(e){setError((e as Error).message)}}
 if(loading)return <div className="center"><div className="spinner"/></div>
 if(!me)return <div className="auth-shell"><form className="login-card" onSubmit={signIn}><div className="brand-mark">TF</div><p className="eyebrow">TASKFLOW</p><h1>Work, with clarity.</h1><p className="muted">Role-aware task management for focused teams.</p><label>Username<input value={login.username} onChange={e=>setLogin({...login,username:e.target.value})} autoFocus/></label><label>Password<input type="password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/></label>{error&&<div className="alert">{error}</div>}<button className="primary wide">Sign in</button><p className="hint">Use the demo accounts from the README.</p></form></div>
 return <div className="app"><aside><div className="side-brand"><span className="brand-mark small">TF</span><div><strong>TaskFlow</strong><small>Role-aware workspace</small></div></div><nav>{[['dashboard','Overview'],['tasks','Tasks'],...(me.role!=='USER'?[['people',me.role==='ADMIN'?'Organization':'Team']]:[])].map(([k,l])=><button key={k} className={view===k?'nav active':'nav'} onClick={()=>setView(k as any)}>{l}</button>)}</nav><div className="side-bottom"><div className={`role-dot ${me.role.toLowerCase()}`}/><div><strong>{me.name||me.username}</strong><small>{me.role}</small></div><button className="ghost" onClick={signOut}>↪</button></div></aside><main><header><div><p className="eyebrow">{me.role}</p><h2>{view==='dashboard'?'Overview':view==='tasks'?'Tasks':me.role==='ADMIN'?'Organization':'Team'}</h2></div><div className="header-actions">{(me.role==='ADMIN'||me.role==='MANAGER')&&<button className="primary" onClick={()=>setShowNew(true)}>+ New task</button>}</div></header>{error&&<div className="alert top">{error}<button onClick={()=>setError('')}>×</button></div>}
 {view==='dashboard'&&<><section className="stats">{[['To do',stats.todo,'todo'],['In progress',stats.progress,'progress'],['Completed',stats.done,'done']].map(([label,num,c])=><div className="stat" key={label as string}><span className={`role-pill ${c}`}>{label}</span><strong>{num}</strong><small>Visible in your scope</small></div>)}</section><section className="panel"><div className="panel-head"><div><h3>Recent work</h3><p className="muted">Latest tasks you can access.</p></div><button className="link" onClick={()=>setView('tasks')}>View all →</button></div><TaskRows tasks={tasks.slice(0,6)} me={me} onStatus={updateStatus} onDelete={remove}/></section></>}
 {view==='tasks'&&<section className="panel"><div className="toolbar"><div className="segmented">{['ALL','TODO','IN_PROGRESS','DONE'].map(s=><button key={s} className={filter===s?'selected':''} onClick={()=>setFilter(s)}>{s==='ALL'?'All':s.replace('_',' ')}</button>)}</div><span className="muted">{filtered.length} tasks</span></div><div className="task-grid">{filtered.map(t=><TaskCard key={t.id} task={t} me={me} onStatus={updateStatus} onDelete={remove}/>)}</div>{filtered.length===0&&<Empty/>}</section>}
 {view==='people'&&<section className="panel"><div className="panel-head"><div><h3>{me.role==='ADMIN'?'Organization':'Your team'}</h3><p className="muted">Authorization is enforced by the API.</p></div></div><div className="people-grid">{users.map(u=><div className="person" key={u.id}><div className={`avatar ${u.role.toLowerCase()}`}>{(u.name||u.username).slice(0,1).toUpperCase()}</div><div><strong>{u.name||u.username}</strong><small>{u.username} · {u.role}</small></div><span className="muted">{u.manager?`Manager #${u.manager}`:'—'}</span></div>)}</div></section>}
 </main>{showNew&&<div className="overlay"><form className="modal" onSubmit={createTask}><div className="panel-head"><div><h3>Create task</h3><p className="muted">Assignment scope is checked server-side.</p></div><button type="button" className="ghost" onClick={()=>setShowNew(false)}>×</button></div><label>Title<input required value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Description<textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Assignee<select required value={draft.assigned_to} onChange={e=>setDraft({...draft,assigned_to:e.target.value})}><option value="">Select a user</option>{users.filter(u=>u.role==='USER'||u.id===me.id).map(u=><option key={u.id} value={u.id}>{u.name||u.username}</option>)}</select></label><div className="row"><button type="button" className="secondary" onClick={()=>setShowNew(false)}>Cancel</button><button className="primary">Create task</button></div></form></div>}</div>
}

function TaskRows({tasks,me,onStatus,onDelete}:{tasks:Task[];me:Me;onStatus:(t:Task,s:string)=>void;onDelete:(t:Task)=>void}){return <div>{tasks.map(t=><div className="task-row" key={t.id}><div><strong>{t.title}</strong><small>{t.assigned_to_name||'Unassigned'} · updated {new Date(t.updated_at).toLocaleDateString()}</small></div><select value={t.status} onChange={e=>onStatus(t,e.target.value)}><option value="TODO">To do</option><option value="IN_PROGRESS">In progress</option><option value="DONE">Done</option></select>{me.role!=='USER'&&<button className="ghost danger" onClick={()=>onDelete(t)}>Delete</button>}</div>)}</div>}
function TaskCard({task,me,onStatus,onDelete}:{task:Task;me:Me;onStatus:(t:Task,s:string)=>void;onDelete:(t:Task)=>void}){return <article className="task-card"><div className="task-card-top"><span className={`role-pill ${task.status.toLowerCase()}`}>{task.status.replace('_',' ')}</span><span className="muted">#{task.id}</span></div><h3>{task.title}</h3><p>{task.description||'No description added.'}</p><div className="task-card-bottom"><span>{task.assigned_to_name||'—'}</span><select value={task.status} onChange={e=>onStatus(task,e.target.value)}><option value="TODO">To do</option><option value="IN_PROGRESS">In progress</option><option value="DONE">Done</option></select>{me.role!=='USER'&&<button className="ghost danger" onClick={()=>onDelete(task)}>×</button>}</div></article>}
function Empty(){return <div className="empty"><div className="empty-icon">✓</div><h3>Nothing here yet</h3><p className="muted">Tasks matching this view will appear here.</p></div>}

createRoot(document.getElementById('root')!).render(<App />)
